/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package compra2.Vista;

import compra2.DataBase.DetalleCompraDataBase;
import compra2.DataBase.ProductoDataBase;
import compra2.Entidades.DetalleCompra;
import compra2.Entidades.Producto;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RODRI
 */
public class ListarProductosMasCompradosEntreFechas extends javax.swing.JInternalFrame {

      private DefaultTableModel modelo= new DefaultTableModel(){
        public boolean isCellEditable(int f, int c){
            return false;
        }
    };
    public ListarProductosMasCompradosEntreFechas() {
        initComponents();
        cabecera();
        llenarTablaInicio();
        hasta.setDate(null);
        desde.setDate(null);
       delimitarFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        desde = new com.toedter.calendar.JDateChooser();
        hasta = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("Listar productos mas vendidos entre fechas");

        jLabel2.setText("Desde");

        jLabel3.setText("hasta");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Reinicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(62, 62, 62)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LlenarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        borrarlista();
        llenarTablaInicio();
        hasta.setDate(null);
        desde.setDate(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser desde;
    private com.toedter.calendar.JDateChooser hasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
          private void cabecera(){
         modelo.addColumn(" Cantidad");
        modelo.addColumn("ID Producto");
          modelo.addColumn("Nombre Producto");
          modelo.addColumn(" Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
       
        jTable1.setModel(modelo);   
    }
public void borrarlista(){
        int a=modelo.getRowCount()-1;
            for(int i=a;i>=0;i--){
             modelo.removeRow(i);
            }
 } 

public void llenarTablaInicio(){
     borrarlista();
    
    try{
           DetalleCompraDataBase pd=new DetalleCompraDataBase();
             
       
      Producto p=new Producto();
          ArrayList<Integer> cantidad = DetalleCompraDataBase.getMasVendido();
          ArrayList<Producto> producto= pd.productoMasComprado();

       Iterator<Producto> iterador = producto.iterator();
       Iterator<Integer> iterador2 = cantidad.iterator();
              
      while( iterador.hasNext()&&iterador2.hasNext()) {
      Producto x=iterador.next();
      Integer z=iterador2.next();
                modelo.addRow(new Object[]{
         z, x.getIdProducto(),x.getNombreProducto(),x.getDescripcion(),x.getPrecioActual(),x.getStock()});
        }
    }catch(NullPointerException e){
        System.out.println("No pasa nada, estan en null po que asi lo quise io.");
    }

    
}

public void LlenarTabla(){
    
    borrarlista();
    
    try{
           DetalleCompraDataBase pd=new DetalleCompraDataBase();
             SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
            String fe = f.format(desde.getDate());
            LocalDate fecha = LocalDate.parse(fe, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        
         String q = f.format(hasta.getDate());
            LocalDate fecha2 = LocalDate.parse(q, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
       
      Producto p=new Producto();
          ArrayList<Integer> cantidad = DetalleCompraDataBase.getMasVendido();
          ArrayList<Producto> producto= pd.productoMasCompradoEntreFechas(fecha, fecha2);

       Iterator<Producto> iterador = producto.iterator();
       Iterator<Integer> iterador2 = cantidad.iterator();
              
      while( iterador.hasNext()&&iterador2.hasNext()) {
      Producto x=iterador.next();
      Integer z=iterador2.next();
                modelo.addRow(new Object[]{
         z, x.getIdProducto(),x.getNombreProducto(),x.getDescripcion(),x.getPrecioActual(),x.getStock()});
        }
    }catch(NullPointerException e){
        System.out.println("No pasa nada, estan en null po que asi lo quise io.");
    }

  }

public void delimitarFecha(){


// Crear un objeto Calendar para representar la fecha de inicio (1 de enero de 2023)
Calendar fechaInicio = Calendar.getInstance();
fechaInicio.set(2023, Calendar.OCTOBER, 1);

// Crear un objeto Calendar para representar la fecha de fin (31 de diciembre de 2023)
Calendar fechaFin = Calendar.getInstance();


// Convertir los objetos Calendar a objetos Date
Date fechaInicioDate = fechaInicio.getTime();
Date fechaFinDate = fechaFin.getTime();

// Establecer el rango de fechas seleccionables en el JDateChooser
desde.setSelectableDateRange(fechaInicioDate, fechaFinDate);
hasta.setSelectableDateRange(fechaInicioDate, fechaFinDate);
}
 
}
////